# vim: shiftwidth=4 tabstop=4 noexpandtab
# Do not modify this file!	It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	imports = [
		(modulesPath + "/installer/scan/not-detected.nix")
		./disko.nix
	];

	boot.initrd.availableKernelModules = [
		"nvme"
		"xhci_pci"
		"ahci"
		"usbhid"
		"usb_storage"
		"uas"
		"sd_mod"
	];
	boot.initrd.kernelModules = [ ];
	boot.kernelModules = [
		"kvm-amd"
	];
	boot.extraModulePackages = with config.boot.kernelPackages; [ v4l2loopback ];

	hardware.amdgpu = {
		initrd.enable = true;
		opencl.enable = true;
	};

	hardware.graphics.enable32Bit = true;

	# Do this here since Lain is different still?
	boot.loader.efi.efiSysMountPoint = "/boot/efi";


	#fileSystems."/" = {
	#	device = "/dev/disk/by-uuid/b63a90b6-1b72-42bd-87d6-71893a1e7d8f";
	#	fsType = "ext4";
	#};
	#
	#fileSystems."/boot" = {
	#	device = "/dev/disk/by-uuid/48CA-0A7A";
	#	fsType = "vfat";
	#};
	#
	#swapDevices = [ ];

	# Enables DHCP on each ethernet and wireless interface. In case of scripted networking
	# (the default) this is the recommended approach. When using systemd-networkd it's
	# still possible to use this option, but it's recommended to use it in conjunction
	# with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
	networking.useDHCP = lib.mkDefault true;
	# networking.interfaces.enp14s0.useDHCP = lib.mkDefault true;

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

